### ISSUE TITLE
See if it's possible to create the string in the config map for JH configuration directly from the value file?

### ISSUE THREAD

**Issue by jdrivas** [Momentlabs/athenaeum#21]
The basic issue:

* templates/hub/ConfigMap.yaml replactes much of the Values file like
```yaml
data:
  config: |-
    hub:
      service:
        type: {{ .Values.hub.service.type }}
```
Not very DRY. 

* We should be able to do something like:

```yaml
data:
  config: |-
    {{ toJson .Values }}
```

* Not sure how or if this works, so it needs investigation

* There is at least one place where this won't really work

In the ConfigMap we find this

```yaml
hub.service.name: {{ include "athenaeum.hub.service.name" }} 
```

This particular example, by the way, is a bug that needs to be fixed, it should set the service name if the .Values equiv is empty.

At any rate this kind of processing needs to occur and may prevent us from taking the Values file directly. 

If the toJson trick does work, then for much of the ConfigMap we can use it, eg

```yaml
data:
  config: |-
    hub: 
       image: {{ toJson .Values.hub.image }}
       service:
           name: {{ include "athenaeum.hub.service.name" }}
           type: {{ .Values.athenaeum.hub.service.type }}
      auth: {{ toJson .Values.hub.auth }}
```

         

```

**Comment by jdrivas** [comment]
So this all works and the file looks something like this now:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: hub-configmap
  labels:
    app: athenaeum
data:
  config: |-
    hub:
      debug: {{ .Values.hub.debug }}
      uid: {{ .Values.hub.uid }}
      fs_gid: {{ .Values.hub.fs_gid }}
      image: {{ .Values.hub.image }}
        # repository: {{ .Values.hub.image.repository }}
        # tag: {{ .Values.hub.image.tag }}
        # pullPolicy: {{ .Values.hub.image.pullPolicy }}
      service:
        name: {{ include "athenaeum.hub.service.name" . }}
        type: {{ .Values.hub.service.type }}
      db: {{ .Values.hub.db }}
        # pvc:
        #   name: {{ .Values.hub.db.pvc.name }}
      auth: {{ .Values.hub.auth }}
        # type: {{ .Values.hub.auth.type }}
        # dummy:
        #   authenticator_class: {{ .Values.hub.auth.dummy.authenticator_class }}
        #   password: {{ .Values.hub.auth.dummy.password }}
        #   whitelist: {{ .Values.hub.auth.dummy.whitelist }}
        # auth0:
        #   authenticator_class: {{ .Values.hub.auth.auth0.authenticator_class }}
        #   client_id: {{ .Values.hub.auth.auth0.client_id }}
        #   client_secret: {{ .Values.hub.auth.auth0.client_secret }}
        #   oauth_callback_url: {{ .Values.hub.auth.auth0.oauth_callback_url }}
        #   auth0_subdomain: {{ .Values.hub.auth.auth0.auth0_subdomain }}
        #   client_redirect_base_url: {{ .Values.hub.auth.auth0.client_redirect_base_url }}
      spawner: {{ toJson .Values.hub.spawner }}
        # spawner_class: {{ .Values.hub.spawner.spawner_class }}
        # start_timeout: {{ .Values.hub.spawner.start_timeout }}
        # image_pull_policy: {{ .Values.hub.spawner.image_pull_policy }}
        # image_spec: {{ .Values.hub.spawner.image_spec }}
        # storage:
        #   user_storage_pvc_ensure: {{ .Values.hub.spawner.storage.user_storage_pvc_ensure }}
        #   user_storage_capacity: {{ .Values.hub.spawner.storage.user_storage_capacity }}
        #   storage_access_modes: {{ .Values.hub.spawner.storage.storage_access_modes }}
        #   pvc_name_template: {{ .Values.hub.spawner.storage.pvc_name_template }}
    proxy:
      hub_should_start: {{ .Values.proxy.hub_should_start }}
      service:
        name: {{ include "athenaeum.proxy.service.name" . }}
        type: {{ .Values.proxy.service.type }}
```
at the risk of getting to clever (read over-engineering) it might make sense to build a helper that allows you to edit the configuration as necessary:

```yaml
data:
  config: |-
    {{- $_ := merge {dict "configEdits": "{"hub": {"service": {"name": {{ include "athenaeum.hub.service.name" . }}
   {{ include "athenaeum.merge_values" $_ }}
 ```

Obviously the syntax above for the edits needs work, it's almost unreadable and complicated to type. Perhaps there is a way to simply read in a file in such a way that this would work, but I seem to remember that reading in a file doesn't enable recursive template evaluation.  So not sure how this could be made to work 

It's a thought though.

The current fix definitely reduces complexity and the error surface significantly so is a good step forward.
